#!/usr/bin/env bash

# mapfile -t arr <sample.txt
mapfile -t arr <input.txt
index=-1
increased=0

for line in "${arr[@]}"; do
  previous="${arr["$index"]}"
  if [ $line -gt $previous ]; then
    increased="$(($increased + 1))"
  fi
  index="$(($index + 1))"
done

echo "Increased $increased times."
