#!/usr/bin/env bash

# mapfile -t ARR1 <sample.txt
mapfile -t ARR1 <input.txt

ARR=()
INDEX1=1
INDEX2=2

for ((i = 0; i < ${#ARR1[@]}; i++)); do
  CURRENT="${ARR1["$i"]}"
  NEXT1="${ARR1["$i" + 1]}"
  NEXT2="${ARR1["$i" + 2]}"
  #TODO: Some arithmetic syntax error here to review later
  WINDOW="$(($CURRENT + $NEXT1 + $NEXT2))"
  ARR+=($WINDOW)
done

INDEX=-1
INCREASED=0

for LINE in "${ARR[@]}"; do
  PREVIOUS="${ARR["$INDEX"]}"
  if [ $LINE -gt $PREVIOUS ]; then
    INCREASED="$(($INCREASED + 1))"
  fi
  INDEX="$(($INDEX + 1))"
done

echo "Increased $INCREASED times."
