#!/usr/bin/env bash

# mapfile -t arr1 <sample.txt
mapfile -t arr1 <input.txt

arr=()
increased=0
len=$((${#arr1[@]} - 2))

for ((i = 0; i < $len; i++)); do
  window=$(expr ${arr1["$i"]} + ${arr1["$i" + 1]} + ${arr1["$i" + 2]})
  arr+=($window)
done

for ((i = 1; i < ${#arr[@]}; i++)); do
  if [ ${arr["$i"]} -gt ${arr["$i" - 1]} ]; then
    let increased++
  fi
done

echo "Increased $increased times."
