#!/usr/bin/env bash

mapfile -t list <sample.txt
# mapfile -t list <input.txt

oxygen=0
co2=0

x_len=$((${#list[@]}))
x_half=$((x_len / 2))
y_len=$((${#list[0]}))

################## sorting out
sort_out() {
  array_in=$1
  prefix=$2
  array_out=()
  len=$((${#array_in[@]}))
  for line in ${array_in[@]}; do
    if [[ "$line" != "$prefix"* ]]; then
      array_out+=(${line:1})
    fi
  done
  echo "${array_out[@]}"
}

prefix="0"
sort_out "${list[*]}" "$prefix"
list2=$(sort_out "${list[*]}" "$prefix")
echo after func "${list2[@]}"

################## sorting_out

for ((i = 0; i < $y_len; i++)); do
  line=()
  for ((j = 0; j < $x_len; j++)); do
    line+=${list[j]:i:1}
  done

  ones=()
  ones=$(echo $line | grep -o '1' | wc -l)
  if [ $ones -gt $x_half ]; then
    echo delete lines starting with zeros
  else
    echo delete lines starting with ones
  fi
done

echo list after everything "${list[@]}"

# life_support= ((oxygen * co2))

echo $life_support is the life support rating of the submarine.
