#!/usr/bin/env bash

# mapfile -t list <sample.txt
mapfile -t list <input.txt

gamma=()
epsilon=()

x_len=$((${#list[@]}))
x_half=$((x_len/2))
y_len=$((${#list[0]}))


for ((i=0; i< $y_len; i++)); do
  line=()
  for ((j = 0; j < $x_len; j++)); do
    line+=${list[j]:i:1}
  done

  ones=()
  ones=$(echo $line | grep -o '1' | wc -l)

  if [ $ones -gt $x_half ]; then
    gamma+=1
    epsilon+=0
  else
    gamma+=0
    epsilon+=1
  fi
done

gamma=$(echo "${gamma[*]}")
epsilon=$(echo "${epsilon[*]}")

gamma=$(echo "$((2#$gamma))")
epsilon=$(echo "$((2#$epsilon))")

power=$((gamma * epsilon))

echo Power consumption of the submarine is $power.
