#!/usr/bin/env bash

mapfile -t list <sample.txt
# mapfile -t list <input.txt

gamma=()
epsilon=()

x_len=$((${#list[@]}))
x_half=$((x_len/2))
y_len=$((${#list[0]}))


for ((i=0; i< $y_len; i++)); do
  line=()
  for ((j = 0; j < $x_len; j++)); do
    # echo counting ${list[j]:0:i}
    line+=${list[j]:i:1}
  done

  ones=()
  ones=$(echo $line | grep -o '1' | wc -l)

  echo line is $line and ones is $ones
  if [ $ones -gt $x_half ]; then
    gamma+=1
    epsilon+=0
  else
    gamma+=0
    epsilon+=1
  fi
done

echo gamma "${gamma[@]}"
echo eplison "${epsilon[@]}"

i=0
n=0

n=$(echo "${gamma[*]}")
echo gamma string is: $n


# Convert binary to decimal
while [ $n -ne 0 ]; do
  digit=$((n % 10))
  num=$((num + digit * 2**i))
  n=$((n / 10))
  let "i++"
done


# Print the result
echo "Resultant Decimal Number: $num"

calc_decimal() {
  return gamma
}
